server:
  port: 8080
  context-path: /boot
  tomcat:
    uri-encoding: utf-8

# 选择环境
spring:
  profiles:
    active: dev

  # 视图层解析
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**