INSERT INTO TBL_USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('jbauer', '24hours', 'Jack', 'Bauer');
INSERT INTO TBL_USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('jbauer1', '24hours', 'Jack1', 'Bauer1');
INSERT INTO TBL_USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('jbauer2', '24hours', 'Jack2', 'Bauer2');
INSERT INTO TBL_USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('jbauer3', '24hours', 'Jack3', 'jbauer3');
INSERT INTO TBL_USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('jbauer4', '24hours', 'jbauer4', 'Bauer4');